package com.bluedream.cliapp.marketplace1.domain;
// Generated 2019/3/30 �U�� 04:14:45 by Hibernate Tools 5.1.7.Final

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import java.time.LocalDateTime;

/**
 * List generated by hbm2java
 */
@Entity
//@Table(name = "list", catalog = "testDB")
@TableGenerator(name="tab", initialValue=100000, allocationSize=50)
public class ListInfo implements java.io.Serializable {

	private long listingId;
	private String title;
	private String description;
	private UserInfo userInfo;
	//private String username;
	private Integer price;	
	private Date createTime;
	//private Calendar createTime;
		private CategoryInfo categoryName;
	//private String categoryName;

	public ListInfo() {
	}

	public ListInfo(UserInfo userInfo, CategoryInfo categoryName) {
		//this.listingId = listingId;
		this.userInfo = userInfo;
		this.categoryName = categoryName;
	}

	public ListInfo(String title, String description, UserInfo userInfo, 
			    Integer price, CategoryInfo categoryName) {
		//this.listingId = listingId;
		this.title = title;
		this.description = description;
		this.userInfo = userInfo;
		this.price = price;		
		this.categoryName = categoryName;
		//this.createTime = Calendar.getInstance();
		//this.createTime = Calendar.getInstance().getTimeInMillis();
		this.createTime = new Date();
	}

	@GeneratedValue(strategy=GenerationType.TABLE, generator="tab")	
	@Id
	@Column(name = "listing_id", unique = true, nullable = false)
	public long getListingId() {
		return this.listingId;
	}

	private void setListingId(long listingId) {
		this.listingId = listingId;
	}

	@Column(name = "title", length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)	
	@JoinColumn(name = "username", nullable = false)
	//@Column(name = "username", nullable = false, length = 50)
	public UserInfo getUserInfo() {
		return this.userInfo;
	}
	
	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

   /*
	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}
	
	public void setUsername(String username) {
		this.username = username;
	}
	*/

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_time", length = 10)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@ManyToOne(fetch = FetchType.EAGER)	
	@JoinColumn(name = "category_name", nullable = false)
	//@Column(name = "category_name", nullable = false, length = 50)
	public CategoryInfo getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(CategoryInfo categoryName) {
		this.categoryName = categoryName;
	}
	
	public String toString(String separator, String displayType) {
		String strRetVal = "";
		String strCreateTime = "";
		
		SimpleDateFormat sdFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		//strCreateTime = sdFormat.format(this.createTime.getTimeInMillis());
		strCreateTime = sdFormat.format(this.createTime);
		// default
		strRetVal = this.title + separator +
		           this.description + separator +
		           this.price.toString() + separator +
		           strCreateTime + separator;
		/*
		if (displayType.equals("SHORT1")) {
			strRetVal = strRetVal + "";	
		} 
		*/		
		if (displayType.equals("FULL")) {
		     strRetVal = strRetVal +
		               this.categoryName.getCategoryName() + separator +
				       this.userInfo.getUsername();
		} 
		
		return strRetVal;
	}

}
